DIR = thread
OBJS  = ConnectionThread.o LoggingThread.o ResolveThread.o LoginThread.o
OBJS += InputThread.o PlayingThread.o SmtpThread.o DatabaseThread.o
OBJS += DatabaseUpgradeThread.o

include ../Makefile.common

