.PHONY:	all clean

#ifeq ("${USING_CYGWIN}", "1")
#CONFARG = --enable-emulate-getaddrinfo
#else
#CONFARG =
#endif 

all:	../../lib/libesmtp.a

../../lib/libesmtp.a:
	autoreconf -f -i -Wall,no-obsolete
	./configure --prefix=`cd ../.. ; pwd` ${CONFARG}
	${MAKE}
	${MAKE} install

clean:
	${MAKE} uninstall
	${MAKE} distclean

