.PHONY:	all clean

PLATFORM := $(shell sh config.guess)
PLATFORM := $(findstring cygwin, $(PLATFORM))
ifeq ("$(PLATFORM)", "cygwin")
CYGWIN  = yes
CONFARG = --enable-emulate-getaddrinfo
else
CYGWIN  =
CONFARG =
endif 

all:	../../lib/libesmtp.a

../../lib/libesmtp.a:
	./configure --prefix=`cd ../.. ; pwd` ${CONFARG}
	${MAKE}
	${MAKE} install

clean:
	${MAKE} uninstall
	${MAKE} distclean

