install-exec-local:	../lib/libhavokcore.a

../lib/libhavokcore.a:	libhavokcore.a
	${INSTALL} -m 644 libhavokcore.a ../lib

uninstall-local:
	${RM} ../lib/libhavokcore.a

all-local:	install-exec-local

clean-local:	uninstall-local
