#
# Makefile.local
#

all-local:
	[ "${MY_SUBDIRS}" != "" ] && \
	for i in ${MY_SUBDIRS} ; do ${MAKE} -C $$i -f Makefile.gjh all ; done

clean-local:
	[ "${MY_SUBDIRS}" != "" ] && \
	for i in ${MY_SUBDIRS} ; do ${MAKE} -C $$i -f Makefile.gjh clean ; done
