#
# Makefile.local
#

all-recursive-local:
	[ "${SUBDIRS}" != "" ] && \
	for i in ${SUBDIRS} ; do ${MAKE} -C $$i -f Makefile.gjh all ; done

clean-recursive-local:
	[ "${SUBDIRS}" != "" ] && \
	for i in ${SUBDIRS} ; do ${MAKE} -C $$i -f Makefile.gjh clean ; done
