CPPFLAGS = -g -std=c++11 -I../ -I ../../../include

LIBFILE = libhavok${DIR}.a

${LIBFILE}:	${OBJS}
	-[ "${OBJS}" != "" ] && ${AR} -crv $@ $+

all:    ${LIBFILE}

clean:
	-[ "${OBJS} ${LIBFILE}" != "" ] && ${RM} ${OBJS} ${LIBFILE}
