install-exec-local:	../lib/libhavokutils.a

../lib/libhavokutils.a:	libhavokutils.a
	${INSTALL} -m 644 libhavokutils.a ../lib

uninstall-local:
	${RM} ../lib/libhavokutils.a

all-local:	install-exec-local

clean-local:	uninstall-local
