.PHONY:	all clean

INSTALL = install
all:	../../lib/libmongoose.a ../../include/mongoose.h

../../lib/libmongoose.a: mongoose.c mongoose.h
	${MAKE} linux COPT=-g
	${MAKE} lib COPT=-g
	${INSTALL} -m 644 libmongoose.a $@

../../include/mongoose.h: mongoose.h
	${INSTALL} -m 644 mongoose.h $@

clean:
	${RM} ../../lib/libmongoose.a ../../include/mongoose.h
	${MAKE} clean
