DIR = objects
OBJS  = Connection.o ConnectionManager.o LoggingSink.o ThreadColors.o
OBJS += ThreadMap.o Account.o Player.o Aggregate.o Settings.o
OBJS += PlayerAttributes.o Dice.o

include ../Makefile.common

